openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a sample API for managing contacts.
tags:
  - name: Contacts
    description: Operations with contacts

servers:
  - url: http://127.0.0.1:3000
  - url: https://project-5-2-tmsp.onrender.com

paths:
  /contacts:
    get:
      $ref: '../swagger/paths/get.yaml'
    post:
      $ref: '../swagger/paths/post.yaml'

  /contacts/{id}:
    get:
      $ref: '../swagger/paths/{id}/get.yaml'
    patch:
      $ref: '../swagger/paths/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/{id}/delete.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
